name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to the branch you want to trigger the deployment from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure the full history is fetched for the gh-pages branch

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'  # Specify the Go version to use

    - name: Install Tweego
      run: |
        git clone https://github.com/tmedwards/tweego.git
        cd tweego
        go mod tidy
        go install
        go build
        cp tweego /usr/local/bin/tweego

    - name: Convert Twee to HTML
      run: |
        # Ensure the directory for HTML files is clean
        mkdir -p output
        tweego -o output/index.html FreeUse.twee

    - name: Upload HTML file
      uses: actions/upload-artifact@v3
      with:
        name: html-files
        path: index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output  # The directory to publish
        publish_branch: gh-pages
        user_name: 'github-actions'
        user_email: 'github-actions@github.com'
        # Optional: Clean the gh-pages branch before publishing
        # clean: true
