name: Convert Twee to HTML

on:
  push:
    branches:
      - main  # Set the branch you want to monitor

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'  # Specify the Go version to use

    - name: Install Tweego
      run: |
        git clone https://github.com/tmedwards/tweego.git
        cd tweego
        go mod tidy          # Download dependencies and update go.sum
        go install
        go build
        cp tweego /usr/local/bin/tweego  # Make sure tweego is in PATH

    - name: Convert Twee to HTML
      run: |
        tweego -o example_1.html FreeUse.twee
        ls -l  # List files to verify the output
        # Add any additional commands to move or handle the HTML file as needed
